 USE lab_mysql;

CREATE TABLE Cars (ID VARCHAR (20)) NOT NULL, VIN VARCHAR(20) NOT NULL, Manufacturer VARCHAR (20) NULL, Model VARCHAR(20) NULL, Year DATE (20) NULL, Color VARCHAR (20) NULL), PRIMARY KEY (VIN));

CREATE TABLE Customers (ID VARCHAR(20) NOT NULL, Customer_ID INT(8) NOT NULL, Phone INT(8) NULL, Email VARCHAR(20) NULL, Address VARCHAR(20) NULL, City VARCHAR(20) NULL, State_Province VARCHAR(20) NULL, Country VARCHAR(20) NULL, Postal VARCHAR(20) NULL), PRIMARY KEY (Customer_ID));

CREATE TABLE Salesperson (ID VARCHAR(20) NOT NULL, Staff_ID INT(20) NULL, Name VARCHAR(20) NULL, Store VARCHAR(20), NULL), PRIMARY KEY (Staff_ID));

CREATE TABLE Invoices (ID VARCHAR(20) NOT NULL, Invoice_number INT(20) NULL, Date DATE NULL, Car VARCHAR(20) NULL, Customer VARCHAR(20) NULL, Sales_person VARCHAR(20) NULL), PRIMARY KEY (Invoice_number)); 